<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Transaction</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4643d8a5-8738-4ca5-bc3a-a79bb062a8e3</testSuiteGuid>
   <testCaseLink>
      <guid>4e09716d-a3d7-4f6b-8a22-6395e8fbd1e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T01 - Pick Product From Detail Product Page</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0905c20-29cb-47d5-a1db-9619989d8782</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92bd698e-45d5-48c1-a41c-0a190bbf7f38</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f16bc304-5df5-4318-944a-2be93ad46a96</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T02 - Pick Product From Homepage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a13cfabe-bd5a-458e-aa83-5b79d42571f1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>72aa085e-023a-4183-8864-422de15a23c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fa082ac-307e-4500-a187-3c0cd71e061f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b018722-6313-4a51-8a58-55341fa798b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T03 - Cart Page - Checkout</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>394fa215-5d41-4692-9488-8068f2492837</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T04 - Cart Page - Remove Item</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>10833e3f-ac82-44c1-a88b-4cdb81122241</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a978c33e-7240-467a-a0cc-110fb6a18e5f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8fb8ad17-f67b-4308-9721-d7e8443236fd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T05 - Cart Page - Continue Shopping</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>58544cea-8e04-4df7-9c7f-c499d7712d84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34399e3c-8bc8-4c41-8e6a-773560887acf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59f3250b-022f-4af5-bb24-d8bae50aea30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T06 - Cart Page - Blank Cart Item</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>599c6611-5374-455b-aa2e-b5d4eaba52e2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T07 - Information Page - Fill Form - Continue</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>faac612d-10d8-4d5e-a641-f5fa25883bfa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01922db5-6a70-4a33-9c72-0103fd13a1af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a598dd37-7c3b-4911-bb4c-ad4c77d6fced</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>80ffeba3-94b5-4780-a795-0d27ca75aeb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T08 - Information Page - Full Name Null</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>feba6b3e-2720-4646-bb9c-8b1e3c3b6189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>974f0b58-ba4d-4fbe-ac4e-555f90c2a1a4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e61b4417-8863-4af9-859b-3fb37574f183</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>48e901e6-1065-4a86-baee-3147f9fc6182</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T09 - Information Page - Last Name Null</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c31bf677-c190-4e5e-87c9-66eff040b4b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c9fcd57-10c3-4b67-975f-47320b239497</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b83653-034c-42ad-800d-0c07a0a7b4ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e729a2d5-87d0-42bb-8ebb-3a5b8e63f762</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T10 - Information Page - Postal Code Null</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>654fe52a-fcc2-4806-b612-8e05e2d9c91e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a31a5fd3-e34e-4231-9202-7cf6c234b3f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e6950a2-1178-44c5-bc8f-25fb7fcf1208</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cce3a6cf-00ae-4968-8e25-ab9905ca5215</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T11 - Information Page - Error X button</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6e2fc53e-a7c5-40a2-afff-968763d1dee0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb61c1e5-7918-430a-b574-28a864b83865</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f61ac05f-3ee4-4ec8-a2ca-af05aa42c399</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d7380cf3-ef07-4d02-a19f-1592b0255168</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Transaction/T12 - Overview Page - Finish</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
