<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS - Login</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e6e07507-190e-43c9-8244-b083d687f98b</testSuiteGuid>
   <testCaseLink>
      <guid>829c8b1b-b9a5-46c1-96cf-6ca4be1e9951</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/L01 - Login Success</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0839a94-11ae-4977-b03b-cbeb711a62a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9950a1cd-892c-4885-99c6-7a1afef11827</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9025b268-e6e6-4663-b63b-5c37be0d42fe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/L02 - Login - Locked Out</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf782703-b1c3-4927-84da-eea4d2d020c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>babb3202-4998-4f3c-9eef-a0c194596ec1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ecb38258-89b1-4845-a516-4bb9532aec35</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/L03 - Login Failed - Invalid username</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ea1ee68-6b40-4803-b8aa-47c5115ee482</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>827bca3f-fc4e-47ef-9abe-b87b704643a1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>67bc85f8-d5cb-4460-baa8-1eaab2dce946</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/L04 - Login Failed - Invalid password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef4a44ec-8d6f-4beb-8f02-0e50aa896653</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d5901eb-f8f4-4d9e-8ae4-fbe9d6ae8fc8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6461afe9-45bb-4d65-927e-59ba66f8cbb1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/L05 - Login Failed - Username Null</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>865c44c7-e592-450d-bac0-52bc08731a28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6622e271-c67f-4490-a832-56d613859285</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a73a6eb3-3cb0-458a-ad32-dd504be5a2a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/L06 - Login Failed - Password Null</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>783bfa74-d67d-47fa-8a64-b0c94a190bf3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4347fea-aa36-4070-8603-a2a1fdb2e630</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
